[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.weather]
verify_jwt = false

[functions.weather-alerts]
verify_jwt = true

[functions.packing-insights]
verify_jwt = true

[functions.google-pollen]
verify_jwt = true

[functions.google-air-quality]
verify_jwt = true

[functions.google-geocoding]
verify_jwt = true

[functions.google-solar]
verify_jwt = true

[functions.validate-apple-receipt]
verify_jwt = true

[functions.apple-notifications]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false

[functions.google-map-tiles]
verify_jwt = false

[functions.google-weather-alerts]
verify_jwt = true
