-- Catalog metadata for svg_clothes_files bucket (files stay in Storage).
create table if not exists public.svg_clothes (
  id            text primary key,
  label         text not null,
  style         text not null check (style in ('feminine', 'masculine', 'neutral')),
  category      text not null check (category in ('tops', 'bottoms', 'outerwear', 'footwear', 'accessories')),
  storage_path  text not null,
  sort_order    int not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists svg_clothes_category_style_idx
  on public.svg_clothes (category, style, sort_order)
  where active;

alter table public.svg_clothes enable row level security;

drop policy if exists "Public read active svg clothes" on public.svg_clothes;
create policy "Public read active svg clothes"
  on public.svg_clothes
  for select
  to public
  using (active = true);

grant select on public.svg_clothes to anon, authenticated;

insert into public.svg_clothes (id, label, style, category, storage_path, sort_order, active)
values
  ('outerwear-neutral-jacket', 'Jacket', 'neutral', 'outerwear', '001-jacket.svg', 0, true),
  ('tops-feminine-dress', 'Dress', 'feminine', 'tops', '002-dress.svg', 1, true),
  ('accessories-neutral-winter-hat', 'Winter Hat', 'neutral', 'accessories', '003-winter-hat.svg', 2, true),
  ('tops-neutral-polo', 'Polo', 'neutral', 'tops', '004-polo.svg', 3, true),
  ('tops-neutral-tshirt', 'Tshirt', 'neutral', 'tops', '005-tshirt.svg', 4, true),
  ('accessories-neutral-gloves', 'Gloves', 'neutral', 'accessories', '006-gloves.svg', 5, true),
  ('outerwear-neutral-jacket-1', 'Jacket 1', 'neutral', 'outerwear', '007-jacket-1.svg', 6, true),
  ('outerwear-neutral-sweater', 'Sweater', 'neutral', 'outerwear', '008-sweater.svg', 7, true),
  ('outerwear-neutral-coat', 'Coat', 'neutral', 'outerwear', '009-coat.svg', 8, true),
  ('bottoms-neutral-trousers', 'Trousers', 'neutral', 'bottoms', '010-trousers.svg', 9, true),
  ('outerwear-neutral-jacket-2', 'Jacket 2', 'neutral', 'outerwear', '011-jacket-2.svg', 10, true),
  ('footwear-masculine-boots', 'Boots', 'masculine', 'footwear', '012-boots.svg', 11, true),
  ('accessories-neutral-winter-hat-1', 'Winter Hat 1', 'neutral', 'accessories', '013-winter-hat-1.svg', 12, true),
  ('tops-feminine-dress-1', 'Dress 1', 'feminine', 'tops', '014-dress-1.svg', 13, true),
  ('footwear-neutral-shoes', 'Shoes', 'neutral', 'footwear', '015-shoes.svg', 14, true),
  ('bottoms-neutral-jeans', 'Jeans', 'neutral', 'bottoms', '016-jeans.svg', 15, true),
  ('tops-neutral-gym', 'Gym', 'neutral', 'tops', '017-gym.svg', 16, true),
  ('tops-neutral-clothes', 'Clothes', 'neutral', 'tops', '018-clothes.svg', 17, true),
  ('tops-neutral-tank-top', 'Tank Top', 'neutral', 'tops', '019-tank-top.svg', 18, true),
  ('accessories-neutral-scarf', 'Scarf', 'neutral', 'accessories', '020-scarf.svg', 19, true),
  ('bottoms-neutral-jeans-1', 'Jeans 1', 'neutral', 'bottoms', '021-jeans-1.svg', 20, true),
  ('bottoms-feminine-tights', 'Tights', 'feminine', 'bottoms', '022-tights.svg', 21, true),
  ('bottoms-masculine-swimming-trunks', 'Swimming Trunks', 'masculine', 'bottoms', '023-swimming-trunks.svg', 22, true),
  ('tops-neutral-clothes-1', 'Clothes 1', 'neutral', 'tops', '024-clothes-1.svg', 23, true),
  ('outerwear-neutral-hoodie', 'Hoodie', 'neutral', 'outerwear', '025-hoodie.svg', 24, true),
  ('tops-neutral-clothing', 'Clothing', 'neutral', 'tops', '026-clothing.svg', 25, true),
  ('footwear-masculine-boot', 'Boot', 'masculine', 'footwear', '027-boot.svg', 26, true),
  ('outerwear-neutral-raincoat', 'Raincoat', 'neutral', 'outerwear', '028-raincoat.svg', 27, true),
  ('outerwear-neutral-pullover', 'Pullover', 'neutral', 'outerwear', '029-pullover.svg', 28, true),
  ('outerwear-neutral-trench-coat', 'Trench Coat', 'neutral', 'outerwear', '030-trench-coat.svg', 29, true),
  ('footwear-neutral-flip-flops', 'Flip Flops', 'neutral', 'footwear', '031-flip-flops.svg', 30, true),
  ('accessories-feminine-pamela-hat', 'Pamela Hat', 'feminine', 'accessories', '032-pamela-hat.svg', 31, true),
  ('tops-feminine-dress-2', 'Dress 2', 'feminine', 'tops', '033-dress-2.svg', 32, true),
  ('bottoms-neutral-shorts', 'Shorts', 'neutral', 'bottoms', '034-shorts.svg', 33, true),
  ('accessories-neutral-umbrella', 'Umbrella', 'neutral', 'accessories', '035-umbrella.svg', 34, true),
  ('outerwear-neutral-overcoat', 'Overcoat', 'neutral', 'outerwear', '036-overcoat.svg', 35, true),
  ('tops-feminine-dress-3', 'Dress 3', 'feminine', 'tops', '037-dress-3.svg', 36, true),
  ('outerwear-neutral-hood', 'Hood', 'neutral', 'outerwear', '038-hood.svg', 37, true),
  ('outerwear-neutral-coat-1', 'Coat 1', 'neutral', 'outerwear', '039-coat-1.svg', 38, true),
  ('tops-feminine-woman-clothes', 'Woman Clothes', 'feminine', 'tops', '040-woman-clothes.svg', 39, true),
  ('tops-feminine-dress-4', 'Dress 4', 'feminine', 'tops', '041-dress-4.svg', 40, true),
  ('tops-neutral-shirt', 'Shirt', 'neutral', 'tops', '042-shirt.svg', 41, true),
  ('tops-feminine-woman-clothes-1', 'Woman Clothes 1', 'feminine', 'tops', '043-woman-clothes-1.svg', 42, true),
  ('tops-neutral-polo-1', 'Polo 1', 'neutral', 'tops', '044-polo-1.svg', 43, true),
  ('tops-neutral-polo-2', 'Polo 2', 'neutral', 'tops', '045-polo-2.svg', 44, true),
  ('tops-neutral-clothes-2', 'Clothes 2', 'neutral', 'tops', '046-clothes-2.svg', 45, true),
  ('tops-feminine-crop-top', 'Crop Top', 'feminine', 'tops', '047-crop-top.svg', 46, true),
  ('tops-neutral-hawaiian-shirt', 'Hawaiian Shirt', 'neutral', 'tops', '048-hawaiian-shirt.svg', 47, true),
  ('footwear-masculine-safety-shoes', 'Safety Shoes', 'masculine', 'footwear', '049-safety-shoes.svg', 48, true),
  ('tops-neutral-sport-clothes', 'Sport Clothes', 'neutral', 'tops', '050-sport-clothes.svg', 49, true),
  ('tops-masculine-uniform', 'Uniform', 'masculine', 'tops', '051-uniform.svg', 50, true),
  ('tops-feminine-dress-5', 'Dress 5', 'feminine', 'tops', '052-dress-5.svg', 51, true),
  ('outerwear-neutral-coat-2', 'Coat 2', 'neutral', 'outerwear', '053-coat-2.svg', 52, true),
  ('tops-neutral-shirt-1', 'Shirt 1', 'neutral', 'tops', '054-shirt-1.svg', 53, true),
  ('accessories-masculine-ear-protection', 'Ear Protection', 'masculine', 'accessories', '055-ear-protection.svg', 54, true),
  ('tops-feminine-woman-clothes-2', 'Woman Clothes 2', 'feminine', 'tops', '056-woman-clothes-2.svg', 55, true),
  ('tops-feminine-woman-clothes-3', 'Woman Clothes 3', 'feminine', 'tops', '057-woman-clothes-3.svg', 56, true),
  ('tops-masculine-wedding-suit', 'Wedding Suit', 'masculine', 'tops', '058-wedding-suit.svg', 57, true),
  ('tops-masculine-suit', 'Suit', 'masculine', 'tops', '059-suit.svg', 58, true),
  ('outerwear-masculine-denim-jacket', 'Denim Jacket', 'masculine', 'outerwear', '060-denim-jacket.svg', 59, true),
  ('tops-neutral-shirt-2', 'Shirt 2', 'neutral', 'tops', '061-shirt-2.svg', 60, true),
  ('outerwear-neutral-coat-3', 'Coat 3', 'neutral', 'outerwear', '062-coat-3.svg', 61, true),
  ('accessories-neutral-hat', 'Hat', 'neutral', 'accessories', '063-hat.svg', 62, true),
  ('accessories-feminine-pamela-hat-1', 'Pamela Hat 1', 'feminine', 'accessories', '064-pamela-hat-1.svg', 63, true),
  ('bottoms-feminine-leggings', 'Leggings', 'feminine', 'bottoms', '065-leggings.svg', 64, true),
  ('bottoms-feminine-skirt', 'Skirt', 'feminine', 'bottoms', '066-skirt.svg', 65, true),
  ('accessories-masculine-safety-glasses', 'Safety Glasses', 'masculine', 'accessories', '067-safety-glasses.svg', 66, true),
  ('tops-masculine-swimsuit', 'Swimsuit', 'masculine', 'tops', '068-swimsuit.svg', 67, true),
  ('tops-neutral-top', 'Top', 'neutral', 'tops', '069-top.svg', 68, true),
  ('tops-masculine-suit-1', 'Suit 1', 'masculine', 'tops', '070-suit-1.svg', 69, true),
  ('bottoms-neutral-loose-pants', 'Loose Pants', 'neutral', 'bottoms', '071-loose-pants.svg', 70, true),
  ('outerwear-neutral-coat-4', 'Coat 4', 'neutral', 'outerwear', '072-coat-4.svg', 71, true),
  ('accessories-feminine-handbag', 'Handbag', 'feminine', 'accessories', '073-handbag.svg', 72, true),
  ('footwear-neutral-shoes-1', 'Shoes 1', 'neutral', 'footwear', '074-shoes-1.svg', 73, true),
  ('tops-neutral-hawaiian-shirt-1', 'Hawaiian Shirt 1', 'neutral', 'tops', '075-hawaiian-shirt-1.svg', 74, true),
  ('bottoms-neutral-shorts-1', 'Shorts 1', 'neutral', 'bottoms', '076-shorts-1.svg', 75, true),
  ('bottoms-feminine-tights-1', 'Tights 1', 'feminine', 'bottoms', '077-tights-1.svg', 76, true),
  ('tops-neutral-sweatshirt', 'Sweatshirt', 'neutral', 'tops', '078-sweatshirt.svg', 77, true),
  ('outerwear-neutral-jacket-3', 'Jacket 3', 'neutral', 'outerwear', '079-jacket-3.svg', 78, true),
  ('accessories-neutral-beanie', 'Beanie', 'neutral', 'accessories', '080-beanie.svg', 79, true),
  ('tops-masculine-swimsuit-1', 'Swimsuit 1', 'masculine', 'tops', '081-swimsuit-1.svg', 80, true),
  ('accessories-neutral-belt', 'Belt', 'neutral', 'accessories', '082-belt.svg', 81, true),
  ('footwear-masculine-boots-1', 'Boots 1', 'masculine', 'footwear', '083-boots-1.svg', 82, true),
  ('footwear-neutral-sneakers', 'Sneakers', 'neutral', 'footwear', '084-sneakers.svg', 83, true),
  ('footwear-feminine-high-heels', 'High Heels', 'feminine', 'footwear', '085-high-heels.svg', 84, true),
  ('footwear-neutral-shoes-2', 'Shoes 2', 'neutral', 'footwear', '086-shoes-2.svg', 85, true),
  ('footwear-masculine-running-shoe', 'Running Shoe', 'masculine', 'footwear', '087-running-shoe.svg', 86, true),
  ('footwear-feminine-heels', 'Heels', 'feminine', 'footwear', '088-heels.svg', 87, true),
  ('footwear-feminine-flat-shoes', 'Flat Shoes', 'feminine', 'footwear', '089-flat-shoes.svg', 88, true),
  ('footwear-neutral-shoes-3', 'Shoes 3', 'neutral', 'footwear', '090-shoes-3.svg', 89, true),
  ('footwear-neutral-sneakers-1', 'Sneakers 1', 'neutral', 'footwear', '091-sneakers-1.svg', 90, true),
  ('footwear-neutral-shoe', 'Shoe', 'neutral', 'footwear', '092-shoe.svg', 91, true),
  ('tops-neutral-tank-top-1', 'Tank Top 1', 'neutral', 'tops', '093-tank-top-1.svg', 92, true),
  ('tops-feminine-girl', 'Girl', 'feminine', 'tops', '094-girl.svg', 93, true),
  ('tops-neutral-tshirt-1', 'Tshirt 1', 'neutral', 'tops', '095-tshirt-1.svg', 94, true),
  ('accessories-neutral-belt-1', 'Belt 1', 'neutral', 'accessories', '096-belt-1.svg', 95, true),
  ('accessories-neutral-sunglasses', 'Sunglasses', 'neutral', 'accessories', '097-sunglasses.svg', 96, true),
  ('accessories-neutral-cap', 'Cap', 'neutral', 'accessories', '098-cap.svg', 97, true),
  ('accessories-feminine-woman-bag', 'Woman Bag', 'feminine', 'accessories', '099-woman-bag.svg', 98, true),
  ('accessories-feminine-shoulder-bag', 'Shoulder Bag', 'feminine', 'accessories', '100-shoulder-bag.svg', 99, true)
on conflict (id) do update set
  label = excluded.label,
  style = excluded.style,
  category = excluded.category,
  storage_path = excluded.storage_path,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = now();
