// AUTO-GENERATED by scripts/classify-svg-files.mjs — do not edit by hand
import type { SvgStyle, SvgCategory } from "@/lib/svgCatalog.types";

export interface SvgCatalogEntry {
  id: string;
  path: string;
  label: string;
  category: SvgCategory;
  style: SvgStyle;
}

export const SVG_CATALOG: SvgCatalogEntry[] = [
  {
    "id": "outerwear-neutral-jacket",
    "path": "neutral/outerwear/001-jacket.svg",
    "label": "Jacket",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-dress",
    "path": "feminine/tops/002-dress.svg",
    "label": "Dress",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "accessories-neutral-winter-hat",
    "path": "neutral/accessories/003-winter-hat.svg",
    "label": "Winter Hat",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-polo",
    "path": "neutral/tops/004-polo.svg",
    "label": "Polo",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-tshirt",
    "path": "neutral/tops/005-tshirt.svg",
    "label": "Tshirt",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-gloves",
    "path": "neutral/accessories/006-gloves.svg",
    "label": "Gloves",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-jacket-1",
    "path": "neutral/outerwear/007-jacket-1.svg",
    "label": "Jacket 1",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-sweater",
    "path": "neutral/outerwear/008-sweater.svg",
    "label": "Sweater",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-coat",
    "path": "neutral/outerwear/009-coat.svg",
    "label": "Coat",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "bottoms-neutral-trousers",
    "path": "neutral/bottoms/010-trousers.svg",
    "label": "Trousers",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-jacket-2",
    "path": "neutral/outerwear/011-jacket-2.svg",
    "label": "Jacket 2",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "footwear-masculine-boots",
    "path": "masculine/footwear/012-boots.svg",
    "label": "Boots",
    "category": "footwear",
    "style": "masculine"
  },
  {
    "id": "accessories-neutral-winter-hat-1",
    "path": "neutral/accessories/013-winter-hat-1.svg",
    "label": "Winter Hat 1",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-dress-1",
    "path": "feminine/tops/014-dress-1.svg",
    "label": "Dress 1",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "footwear-neutral-shoes",
    "path": "neutral/footwear/015-shoes.svg",
    "label": "Shoes",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "bottoms-neutral-jeans",
    "path": "neutral/bottoms/016-jeans.svg",
    "label": "Jeans",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-gym",
    "path": "neutral/tops/017-gym.svg",
    "label": "Gym",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-clothes",
    "path": "neutral/tops/018-clothes.svg",
    "label": "Clothes",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-tank-top",
    "path": "neutral/tops/019-tank-top.svg",
    "label": "Tank Top",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-scarf",
    "path": "neutral/accessories/020-scarf.svg",
    "label": "Scarf",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "bottoms-neutral-jeans-1",
    "path": "neutral/bottoms/021-jeans-1.svg",
    "label": "Jeans 1",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "bottoms-feminine-tights",
    "path": "feminine/bottoms/022-tights.svg",
    "label": "Tights",
    "category": "bottoms",
    "style": "feminine"
  },
  {
    "id": "bottoms-masculine-swimming-trunks",
    "path": "masculine/bottoms/023-swimming-trunks.svg",
    "label": "Swimming Trunks",
    "category": "bottoms",
    "style": "masculine"
  },
  {
    "id": "tops-neutral-clothes-1",
    "path": "neutral/tops/024-clothes-1.svg",
    "label": "Clothes 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-hoodie",
    "path": "neutral/outerwear/025-hoodie.svg",
    "label": "Hoodie",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-clothing",
    "path": "neutral/tops/026-clothing.svg",
    "label": "Clothing",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "footwear-masculine-boot",
    "path": "masculine/footwear/027-boot.svg",
    "label": "Boot",
    "category": "footwear",
    "style": "masculine"
  },
  {
    "id": "outerwear-neutral-raincoat",
    "path": "neutral/outerwear/028-raincoat.svg",
    "label": "Raincoat",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-pullover",
    "path": "neutral/outerwear/029-pullover.svg",
    "label": "Pullover",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-trench-coat",
    "path": "neutral/outerwear/030-trench-coat.svg",
    "label": "Trench Coat",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "footwear-neutral-flip-flops",
    "path": "neutral/footwear/031-flip-flops.svg",
    "label": "Flip Flops",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "accessories-feminine-pamela-hat",
    "path": "feminine/accessories/032-pamela-hat.svg",
    "label": "Pamela Hat",
    "category": "accessories",
    "style": "feminine"
  },
  {
    "id": "tops-feminine-dress-2",
    "path": "feminine/tops/033-dress-2.svg",
    "label": "Dress 2",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "bottoms-neutral-shorts",
    "path": "neutral/bottoms/034-shorts.svg",
    "label": "Shorts",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-umbrella",
    "path": "neutral/accessories/035-umbrella.svg",
    "label": "Umbrella",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-overcoat",
    "path": "neutral/outerwear/036-overcoat.svg",
    "label": "Overcoat",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-dress-3",
    "path": "feminine/tops/037-dress-3.svg",
    "label": "Dress 3",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "outerwear-neutral-hood",
    "path": "neutral/outerwear/038-hood.svg",
    "label": "Hood",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-coat-1",
    "path": "neutral/outerwear/039-coat-1.svg",
    "label": "Coat 1",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-woman-clothes",
    "path": "feminine/tops/040-woman-clothes.svg",
    "label": "Woman Clothes",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-feminine-dress-4",
    "path": "feminine/tops/041-dress-4.svg",
    "label": "Dress 4",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-neutral-shirt",
    "path": "neutral/tops/042-shirt.svg",
    "label": "Shirt",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-woman-clothes-1",
    "path": "feminine/tops/043-woman-clothes-1.svg",
    "label": "Woman Clothes 1",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-neutral-polo-1",
    "path": "neutral/tops/044-polo-1.svg",
    "label": "Polo 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-polo-2",
    "path": "neutral/tops/045-polo-2.svg",
    "label": "Polo 2",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-clothes-2",
    "path": "neutral/tops/046-clothes-2.svg",
    "label": "Clothes 2",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-crop-top",
    "path": "feminine/tops/047-crop-top.svg",
    "label": "Crop Top",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-neutral-hawaiian-shirt",
    "path": "neutral/tops/048-hawaiian-shirt.svg",
    "label": "Hawaiian Shirt",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "footwear-masculine-safety-shoes",
    "path": "masculine/footwear/049-safety-shoes.svg",
    "label": "Safety Shoes",
    "category": "footwear",
    "style": "masculine"
  },
  {
    "id": "tops-neutral-sport-clothes",
    "path": "neutral/tops/050-sport-clothes.svg",
    "label": "Sport Clothes",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-masculine-uniform",
    "path": "masculine/tops/051-uniform.svg",
    "label": "Uniform",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "tops-feminine-dress-5",
    "path": "feminine/tops/052-dress-5.svg",
    "label": "Dress 5",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "outerwear-neutral-coat-2",
    "path": "neutral/outerwear/053-coat-2.svg",
    "label": "Coat 2",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-shirt-1",
    "path": "neutral/tops/054-shirt-1.svg",
    "label": "Shirt 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "accessories-masculine-ear-protection",
    "path": "masculine/accessories/055-ear-protection.svg",
    "label": "Ear Protection",
    "category": "accessories",
    "style": "masculine"
  },
  {
    "id": "tops-feminine-woman-clothes-2",
    "path": "feminine/tops/056-woman-clothes-2.svg",
    "label": "Woman Clothes 2",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-feminine-woman-clothes-3",
    "path": "feminine/tops/057-woman-clothes-3.svg",
    "label": "Woman Clothes 3",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-masculine-wedding-suit",
    "path": "masculine/tops/058-wedding-suit.svg",
    "label": "Wedding Suit",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "tops-masculine-suit",
    "path": "masculine/tops/059-suit.svg",
    "label": "Suit",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "outerwear-masculine-denim-jacket",
    "path": "masculine/outerwear/060-denim-jacket.svg",
    "label": "Denim Jacket",
    "category": "outerwear",
    "style": "masculine"
  },
  {
    "id": "tops-neutral-shirt-2",
    "path": "neutral/tops/061-shirt-2.svg",
    "label": "Shirt 2",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-coat-3",
    "path": "neutral/outerwear/062-coat-3.svg",
    "label": "Coat 3",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-hat",
    "path": "neutral/accessories/063-hat.svg",
    "label": "Hat",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "accessories-feminine-pamela-hat-1",
    "path": "feminine/accessories/064-pamela-hat-1.svg",
    "label": "Pamela Hat 1",
    "category": "accessories",
    "style": "feminine"
  },
  {
    "id": "bottoms-feminine-leggings",
    "path": "feminine/bottoms/065-leggings.svg",
    "label": "Leggings",
    "category": "bottoms",
    "style": "feminine"
  },
  {
    "id": "bottoms-feminine-skirt",
    "path": "feminine/bottoms/066-skirt.svg",
    "label": "Skirt",
    "category": "bottoms",
    "style": "feminine"
  },
  {
    "id": "accessories-masculine-safety-glasses",
    "path": "masculine/accessories/067-safety-glasses.svg",
    "label": "Safety Glasses",
    "category": "accessories",
    "style": "masculine"
  },
  {
    "id": "tops-masculine-swimsuit",
    "path": "masculine/tops/068-swimsuit.svg",
    "label": "Swimsuit",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "tops-neutral-top",
    "path": "neutral/tops/069-top.svg",
    "label": "Top",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-masculine-suit-1",
    "path": "masculine/tops/070-suit-1.svg",
    "label": "Suit 1",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "bottoms-neutral-loose-pants",
    "path": "neutral/bottoms/071-loose-pants.svg",
    "label": "Loose Pants",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-coat-4",
    "path": "neutral/outerwear/072-coat-4.svg",
    "label": "Coat 4",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "accessories-feminine-handbag",
    "path": "feminine/accessories/073-handbag.svg",
    "label": "Handbag",
    "category": "accessories",
    "style": "feminine"
  },
  {
    "id": "footwear-neutral-shoes-1",
    "path": "neutral/footwear/074-shoes-1.svg",
    "label": "Shoes 1",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-hawaiian-shirt-1",
    "path": "neutral/tops/075-hawaiian-shirt-1.svg",
    "label": "Hawaiian Shirt 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "bottoms-neutral-shorts-1",
    "path": "neutral/bottoms/076-shorts-1.svg",
    "label": "Shorts 1",
    "category": "bottoms",
    "style": "neutral"
  },
  {
    "id": "bottoms-feminine-tights-1",
    "path": "feminine/bottoms/077-tights-1.svg",
    "label": "Tights 1",
    "category": "bottoms",
    "style": "feminine"
  },
  {
    "id": "tops-neutral-sweatshirt",
    "path": "neutral/tops/078-sweatshirt.svg",
    "label": "Sweatshirt",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "outerwear-neutral-jacket-3",
    "path": "neutral/outerwear/079-jacket-3.svg",
    "label": "Jacket 3",
    "category": "outerwear",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-beanie",
    "path": "neutral/accessories/080-beanie.svg",
    "label": "Beanie",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "tops-masculine-swimsuit-1",
    "path": "masculine/tops/081-swimsuit-1.svg",
    "label": "Swimsuit 1",
    "category": "tops",
    "style": "masculine"
  },
  {
    "id": "accessories-neutral-belt",
    "path": "neutral/accessories/082-belt.svg",
    "label": "Belt",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "footwear-masculine-boots-1",
    "path": "masculine/footwear/083-boots-1.svg",
    "label": "Boots 1",
    "category": "footwear",
    "style": "masculine"
  },
  {
    "id": "footwear-neutral-sneakers",
    "path": "neutral/footwear/084-sneakers.svg",
    "label": "Sneakers",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "footwear-feminine-high-heels",
    "path": "feminine/footwear/085-high-heels.svg",
    "label": "High Heels",
    "category": "footwear",
    "style": "feminine"
  },
  {
    "id": "footwear-neutral-shoes-2",
    "path": "neutral/footwear/086-shoes-2.svg",
    "label": "Shoes 2",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "footwear-masculine-running-shoe",
    "path": "masculine/footwear/087-running-shoe.svg",
    "label": "Running Shoe",
    "category": "footwear",
    "style": "masculine"
  },
  {
    "id": "footwear-feminine-heels",
    "path": "feminine/footwear/088-heels.svg",
    "label": "Heels",
    "category": "footwear",
    "style": "feminine"
  },
  {
    "id": "footwear-feminine-flat-shoes",
    "path": "feminine/footwear/089-flat-shoes.svg",
    "label": "Flat Shoes",
    "category": "footwear",
    "style": "feminine"
  },
  {
    "id": "footwear-neutral-shoes-3",
    "path": "neutral/footwear/090-shoes-3.svg",
    "label": "Shoes 3",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "footwear-neutral-sneakers-1",
    "path": "neutral/footwear/091-sneakers-1.svg",
    "label": "Sneakers 1",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "footwear-neutral-shoe",
    "path": "neutral/footwear/092-shoe.svg",
    "label": "Shoe",
    "category": "footwear",
    "style": "neutral"
  },
  {
    "id": "tops-neutral-tank-top-1",
    "path": "neutral/tops/093-tank-top-1.svg",
    "label": "Tank Top 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "tops-feminine-girl",
    "path": "feminine/tops/094-girl.svg",
    "label": "Girl",
    "category": "tops",
    "style": "feminine"
  },
  {
    "id": "tops-neutral-tshirt-1",
    "path": "neutral/tops/095-tshirt-1.svg",
    "label": "Tshirt 1",
    "category": "tops",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-belt-1",
    "path": "neutral/accessories/096-belt-1.svg",
    "label": "Belt 1",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-sunglasses",
    "path": "neutral/accessories/097-sunglasses.svg",
    "label": "Sunglasses",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "accessories-neutral-cap",
    "path": "neutral/accessories/098-cap.svg",
    "label": "Cap",
    "category": "accessories",
    "style": "neutral"
  },
  {
    "id": "accessories-feminine-woman-bag",
    "path": "feminine/accessories/099-woman-bag.svg",
    "label": "Woman Bag",
    "category": "accessories",
    "style": "feminine"
  },
  {
    "id": "accessories-feminine-shoulder-bag",
    "path": "feminine/accessories/100-shoulder-bag.svg",
    "label": "Shoulder Bag",
    "category": "accessories",
    "style": "feminine"
  }
];

export const SVG_CATALOG_BY_ID: Record<string, SvgCatalogEntry> = Object.fromEntries(
  SVG_CATALOG.map((e) => [e.id, e])
);

/** Maps legacy React registry keys (PascalCase) to stable catalog ids. */
export const LEGACY_SVG_KEY_MAP: Record<string, string> = {
  TShirt: 'tops-neutral-tshirt',
  LongSleeve: 'tops-neutral-shirt',
  Sweater: 'outerwear-neutral-sweater',
  Dress: 'tops-feminine-dress',
  Jacket: 'outerwear-neutral-jacket',
  HeavyJacket: 'outerwear-neutral-jacket-1',
  HeavyCoat: 'outerwear-neutral-coat',
  RainJacket: 'outerwear-neutral-raincoat',
  WomensJacket: 'outerwear-neutral-jacket-3',
  Pants: 'bottoms-neutral-trousers',
  Shorts: 'bottoms-neutral-shorts',
  WomensJeans: 'bottoms-neutral-jeans',
  Sneakers: 'footwear-neutral-sneakers',
  FlipFlops: 'footwear-neutral-flip-flops',
  SnowBoots: 'footwear-masculine-boots',
  RainBoots: 'footwear-masculine-boot',
  Umbrella: 'accessories-neutral-umbrella',
  Sunglasses: 'accessories-neutral-sunglasses',
  Scarf: 'accessories-neutral-scarf',
  Beanie: 'accessories-neutral-beanie',
  Gloves: 'accessories-neutral-gloves',
};

export function resolveSvgId(value: string | null | undefined): string | null {
  if (!value) return null;
  if (SVG_CATALOG_BY_ID[value]) return value;
  return LEGACY_SVG_KEY_MAP[value] ?? value;
}
